### ISSUE TITLE
These counts are not normalised and should not be log transformed

### ISSUE THREAD

**Issue by markziemann** [casbap/ncRNA#12]
https://github.com/casbap/ncRNA/blob/be6aaec0a16972995b8288d8ab56ff908977df57/HumanClusters.Rmd#L32

**Comment by markziemann** [comment]
@casbap can you advise on whether this expression data needs to be normalised (cpm), log transformed, scaled or not? Ditto on all other times the expression data is used.

**Comment by casbap** [comment]
> @casbap can you advise on whether this expression data needs to be normalised (cpm), log transformed, scaled or not? Ditto on all other times the expression data is used.

needs to be log-transformed for the large dataset as distributions cannot be modeled well on a ggplot otherwise. The normalised log transformation is overlal better for stat analysis
