### ISSUE TITLE
normAggScale does not exist anymore

### ISSUE THREAD

**Issue by markziemann** [casbap/ncRNA#18]
https://github.com/casbap/ncRNA/blob/4d63b3c93f94edc63ecea2a35694447a7bd2d0ad/HumanGoPrep.Rmd#L134

```
normAggScale <- readRDS("normAggScale.rds")
```

The object `normAggScale` does not exist in this analysis anymore! Can you fix?

Please update the other scripts so that all the readRDS and saveRDS commands work as expected?

**Comment by casbap** [comment]
fixed in ImputationBlinded & Imputation stages - needed to be normAggLog // normAggLog_test respectively
