### ISSUE TITLE
HumanImputationBlinded

### ISSUE THREAD

**Issue by markziemann** [casbap/ncRNA#20]
> sample_kfold <- optimise_impute(cl_list, thresh, cutClustvalues_dynamic, normAggLog, GO_train)
[1] "2407"
[1] 0.1
Error in corr_per_clust(normAggLog, cutClust, clust_total) : 
  object 'cutClust' not found

**Comment by casbap** [comment]
cutClust loaded in script and optimse_inpute should be functioning more efficiently now
