### ISSUE TITLE
optimise_impute() problem

### ISSUE THREAD

**Issue by markziemann** [casbap/ncRNA#21]
https://github.com/casbap/ncRNA/blob/1669f51ae3327b34d35b9bf9a43d20f8f7a9d639/HumanImputationBlinded.Rmd#L93

There is a major problem with the functions. This is a showstopper meaning we can't proceed without fixing this problem.

```
label: coarsesweep1
Quitting from lines 73-104 (HumanImputationBlinded.Rmd) 
Error in y$ClusterNumber : $ operator is invalid for atomic vectors
```

Specifically this command is broken:

```
> sample_kfold <- optimise_impute(cl_list, thresh, cutClustvalues_dynamic,
+   normAggLog, GO_train, cutClust)
[1] "2407"
[1] 0.1
Error in y$ClusterNumber : $ operator is invalid for atomic vectors
```

The error message suggests the problem is  with the `corr_per_clust()` function.

Some other points:
* each function should have the structure `func(arg=var, arg=var, arg=var)` so it is explicit what inputs are used.
* I'm not sure what `cl_list` should be. Is it the total number of clusters or is it a vector of cluster sizes?

**Comment by casbap** [comment]
function structure fixed in necessary scripts
cl_list is a vector list of cluster sizes (lengths) found within the cutClust variable. This isolates unique cluster lengths that correspond to individual clusters for analysis
