### ISSUE TITLE
ERROR: undefined columns

### ISSUE THREAD

**Issue by casbap** [casbap/ncRNA#8]
https://github.com/casbap/ncRNA/blob/113a082970e75e3b8ceacf423a0efc7f56327e87/HumanDataPrep.Rmd#L138

<html>
<body>

Error in `[.data.frame`(x[[IDX]], , srrs) : undefined columns selected
--
 
  |  
 

<br class="Apple-interchange-newline">
</body>
</html>

dataframe conjunction not recognising columns - may be due to new refined dataset
orgCountMetadata is also created as a list, so the duel dataframe cannot read it currently

**Comment by casbap** [comment]
same issue:

line 102, chunk 4 HumanDataPrep
)
> orgPassWide <- as.data.frame(orgPassWide)
> rownames(orgPassWide) <- orgPassWide[,1]
> orgPassWide <- orgPassWide[,-1]
> orgPassWide[1:10,1:6]
Error in `[.data.frame`(orgPassWide, 1:10, 1:6) : 
  undefined columns selected

**Comment by markziemann** [comment]
Apologies - there was an error with the file I provided. Gene names and sample names were swapped. I've fixed it now so you can git it a try again
